namespace SpriteKind {
    export const Boomerang = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Satellite, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    otherSprite.setVelocity(-30, -30)
    if (!(hasShownMission)) {
        game.showLongText("Your Mission is to drive annoying Satellite Away!", DialogLayout.Bottom)
        hasShownMission = true
    }
    animation.runImageAnimation(
    projectile,
    [img`
        ................
        ..........111...
        ..........111...
        .....4...441....
        .....44..441....
        .....44444.1....
        ....7.444c.1....
        ....4.544..7....
        ....4.544c.4....
        ....4.5444.4....
        ....44996644....
        ....44968644....
        .....699886.....
        .....669868.....
        .....699868.....
        ....46696664....
        ....44444444....
        ....4..444.4....
        ....4..444..4...
        ...4....44..4...
        ..4....444...4.7
        .7....444.....4.
        ......44........
        .......4........
        `,img`
        ................
        ................
        ................
        .....4...44.....
        .....44..4111...
        .....44444111...
        ....7.444c.1....
        ....4.544..1....
        ....4.544c.7....
        ....4.5444.4....
        ....44996644....
        ....44968644....
        .....699886.....
        .....669868.....
        .....699868.....
        ....46696664....
        ....44444444....
        ....4..444.4....
        ....4..444..4...
        ...4....44..4...
        ..4.....44...4..
        .7......44....7.
        ........44......
        .........4......
        `,img`
        ................
        ................
        ................
        .....4...44.....
        .....44..44.....
        .....44444111...
        ......444c111...
        ....7.544..1....
        ....4.544c.1....
        ....4.5444.4....
        ....44996644....
        ....44968644....
        .....699886.....
        .....669868.....
        .....699868.....
        ....46696664....
        ....44444444....
        ....4..444.4....
        ....4..444..4...
        ...4....44..44..
        ..4.....44...77.
        .7......444.....
        .........444....
        ...........4....
        `,img`
        ................
        ................
        ................
        .....4...4111...
        .....44..4111...
        .....44444.1....
        ......444c.1....
        ......544..1....
        ....7.544c.4....
        ....4.5444.4....
        ....44996644....
        ....44968644....
        .....699886.....
        .....669868.....
        .....699868.....
        ....46696664....
        ....44444444....
        ....4.444..4....
        ....4..444..4...
        ...7....44..4...
        ........444..44.
        .........444..77
        ...........444..
        ................
        `],
    50,
    true
    )
    sprite.sayText("Go Away!", 500, true)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    // To prevent the player from creating a new kangaroo until the active one is collected/destroyed
    if (!(hasKangaroo)) {
        hasKangaroo = true
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . 
            `, myShip, 0, -60)
        controller.moveSprite(projectile, 60, 30)
        // 2. Wait for a specific duration (e.g., 500 ms)
        timer.after(1000, function () {
            // 3. Stop movement completely at this location
            projectile.setVelocity(0, 0)
        })
        // change kind to Boomerang or any kind other than projectile to not trigger right now
        projectile.setKind(SpriteKind.Boomerang)
        animation.runImageAnimation(
        projectile,
        [img`
            ................
            ................
            ................
            .....4...44.....
            .....44..44.....
            .....44444......
            ....7.444c......
            ....4.544..7....
            ....4.544c.4....
            ....4.5444.4....
            ....44996644....
            ....44968144....
            .....699186.....
            .....661868.....
            .....119868.....
            ....41196664....
            ....44444444....
            ....4..444.4....
            ....4..444..4...
            ...4....44..4...
            ..4....444...4.7
            .7....444.....4.
            ......44........
            .......4........
            `,img`
            ................
            ................
            ................
            .....4...44.....
            .....44..44.....
            .....44444......
            ....7.444c......
            ....4.544.......
            ....4.544c.7....
            ....4.5444.4....
            ....44996144....
            ....44961644....
            .....691886.....
            .....119868.....
            .....119868.....
            ....46696664....
            ....44444444....
            ....4..444.4....
            ....4..444..4...
            ...4....44..4...
            ..4.....44...4..
            .7......44....7.
            ........44......
            .........4......
            `,img`
            ................
            ................
            ................
            .....4...44.....
            .....44..44.....
            .....44444......
            ......444c.7....
            ....7.544..4....
            ....4.544c.4....
            ....4.5441.4....
            ....44991644....
            ....44918644....
            .....119886.....
            .....119868.....
            .....699868.....
            ....46696664....
            ....44444444....
            ....4..444.4....
            ....4..444..4...
            ...4....44..44..
            ..4.....44...77.
            .7......444.....
            .........444....
            ...........4....
            `,img`
            ................
            ................
            ................
            .....4...44.....
            .....44..44.....
            .....44444......
            ......444c.7....
            ......544..4....
            ....7.544c.4....
            ....4.544414....
            ....44996144....
            ....44961644....
            .....691886.....
            .....119868.....
            .....119868.....
            ....46696664....
            ....44444444....
            ....4.444..4....
            ....4..444..4...
            ...7....44..4...
            ........444..44.
            .........444..77
            ...........444..
            ................
            `],
        500,
        true
        )
        projectile.setStayInScreen(true)
        timer.after(600, function () {
            // Change the kind of projectile to not trigger the Sprite destory
            projectile.setKind(SpriteKind.Projectile)
        })
    }
})
// 2. Destroys the projectile when it overlaps your ship
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
    sprite.destroy(effects.smiles, 100)
    hasKangaroo = false
    otherSprite.sayText("Gotcha!", 2000, false)
    otherSprite.sayText("Press A to deploy Roo Again!", 1000, false)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    sprites.destroyAllSpritesOfKind(SpriteKind.Satellite)
    game.showLongText("Roo is hit by Meteoroid! Come Back!", DialogLayout.Bottom)
    // Make small roo instantly rush back to ship
    otherSprite.follow(myShip, 250)
    myRock.setVelocity(0, 0)
    otherSprite.sayText("Coming!", 5000, false)
    game.showLongText("Comfirm!", DialogLayout.Bottom)
    hasKangaroo = false
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    scene.cameraShake(4, 500)
    sprite.destroy(effects.disintegrate, 100)
    info.changeLifeBy(-1)
})
info.onLifeZero(function () {
    if (info.score() == accessCode) {
        game.setGameOverMessage(true, "Access Granted")
        game.setGameOverPlayable(true, music.melodyPlayable(music.magicWand), false)
        light.showAnimation(light.rainbowAnimation, 500)
        pins.D5.servoWrite(openBox)
        game.gameOver(true)
    } else {
        game.setGameOverMessage(false, "GAME OVER!")
        game.gameOver(false)
    }
})
info.onScore(200, function () {
    game.gameOver(true)
})
let mySat: Sprite = null
let myRock: Sprite = null
let hasKangaroo = false
let projectile: Sprite = null
let myShip: Sprite = null
let openBox = 0
let accessCode = 0
let hasShownMission = false
hasShownMission = false
accessCode = 13
let closeBox = 45
openBox = 120
pins.D5.servoWrite(closeBox)
game.splash("Captain Roo's Mission")
scene.setBackgroundImage(img`
    ccccccccccccceeeeeeeeeffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccddffffdeee9efeeeeeeeeeeeedeecddf
    cfcccfcccccddddccceeeffcffd9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccffffddeeeeeeeeeeeeeeeeeeeeeeefdd
    cccffccccccffffddeeeecccfff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffccddefeedeeeeeeeeeeeeeeefeeeeeeeefdd
    cccfffffcccccccccddfccccfff99fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccceeeeedbeeeeeeeeeeeeeeeefeeeeeeeccd
    ccfffffffccfccccccfbfffeffff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccceeeedeeeeedeeeeeeeedeeeeeeeeeeeecd
    fcfffffffffffccccccbffffffcff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdeeeedeedeeeeedeeeeeeeeeeeedeeeeeecd
    ccffffffffffffcccccebffffffcf9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcceeeedeeebeeeeeeedeeeeeeeedeeeeeeeeff
    ccffffffffffffffcccfbfefffcff99ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffcdceeedeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeff
    cffffffffffffffffcccbffffccccf9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffccdcccdeeeeeeeeeeeeeeeeeedeeeeedeeeeeedf
    cfffffffffffffffffcccdffdffcff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffccdcccdeeeeeeeeeeeeeeeeeeeeeeeeeeeefeeef
    ffffffffffffffffffcccfdffffcfff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffbeccfffccdccedeeeedbdeeeddeeeeeeeeeeeeeeeeedfeef
    ffffffffffffffffffffccfcfbfffff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffeeccffcccdccdeeedeeeedeeeeeeeededeedeeeeeeecdeed
    ffffffffffffffffffffcccdfcffbfff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffccdcffccdecbcceeeeeeeeeeeedeeeeddeeeeeeedeeeeeed
    cffffffffffffffffffffcccffefffff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffcccdccfceeccdceeeeeeeeebeeeeeeeedddeeeeeeeeeeeeec
    cfffffffffffffffffffffccdffcfcccf9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffcccdccfcdcceccceeeeeeeedeeeeeeeeeddeeeeeeeeeeeeee
    ffffffffffffffffffffffcccdfdfcbccd9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffccccccccdccdcccceeededeeeeeeedeeeeeeeedeeeedeeeee
    ffffffffffffffffffffffcfcdffdcfccc9ffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffefffffffcccdcccdccecccbeeeeeeeeeedeeeeeeeeeeeeedeeeeeeee
    fffffffffffffffffffffffcfdfffdccccb9fffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffefffffccccddccbddedddbdeeeeeeeeeeeeeeeeeeeeeeeeeeeeeede
    ffffffffffffffffffffffffcfdfccccccf9fffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffefffffcfcccccbdccccccddddeeebeeeeeeeeeddeeeeeeeeeeeeede
    fffffffffffffffffffffffffff9cccccccd9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffccccdcc9cccccccddeedeeeeeedeeeedddeeeeeeeeeede
    fffffffffffffffffffffffffffd9ccdcccf9efffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffeefffffffccccdcc99cebccccceeeeeeeeeeeeeeeeeddeeeeededee
    ffffffffffffffffffffffffffffdfcccdcf9dfffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffeeffccfcccccdcccbcc59cccbeeeeeedeeeeeeeeeeeeeeeeeebbee
    ffffffffffffffffffffffffffff99ccdfcc9dfffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffceeeebfbbdcdbcdcbcc55eccceeeeeeeeeeeeeeeeeeeeeeeeedeee
    fffffffffffffffffffffffffffff9cccbccf9dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccdcbcccccc59cdcccdebdeeeeeeeedeeeedeeeeddeee
    fffffffffffffffffffffffffffff9fcfddfffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfccccdcbcccccccccccccccdeeeebeeeeeeeeeeeeeedcede
    ffffffffffffffffffffffffffffff9fffdcff9fffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffcccbbdccccedddccddccdeeeeebeeeeeeeeeeeddeedee
    ffffffffffffffffffffffffffffff9dfffdff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcdccdddbcccccbeccdeeddebcbeeeeeeeeeeeceedee
    fffffffffffffffffffffffffffffff9fccbdff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcbdccccdccccdccccdcbccdceeeceeeeeddeeeedcee
    fffffffffffffffffffffffffffffffd9ccfdff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdcccceccccdccccdcbecde9edbcccddeedcedcffc
    ffffffffffffffffffffffffffffffffd9ffdff9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffcccdcccbeccebcdcccdccccc559cdccccccecddffffc
    fffffffffffffffffffffffffffffffff9fcfdcfdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfffffffffffffccbbcccdcdeccdcccdcccccc5dccbdcddccdddcffffc
    ffffffffffffffffffffffffffffffffff9ffbcff9ffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffcffffffccddccccdcbcccdcccdcccccc5dc9cdceeddebccccccc
    ffffffffffffffffffffffffffffffffffdffcdffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffdecdccdceceedccdeeedcccccdccdccdccdbccccccc
    fffffffffffffffffffffffffffffffffff9ffdff99ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffdecdcedecccceccdccceccccccdecededdcccccccec
    fffffffffffffffffffffffffffffffffffd9ffdffcffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffdfcbcccdcccccddbccdcccdcccddcbdddcccccccfcf
    ffffffffffffffffffffffffffffffffffff9ffcdfcfffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffdccdccccdcccceccbdcdcccccccdcbccccccccdbfcf
    ffffffffffffffffffffffffffffffffffffdfffdff6cfffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffdccdcccccdcddbccccccccccdecddedcccffcdccfff
    fffffffffffffffffffffffffffffffffffff6fffdcfcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdccdedcccccccccccccecdddddccccedccfffcfcffff
    ffffffffffffffffffffffffffffffffffffff6ffdccf9ffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffdccdedcccccccccccdcccccbcccceddccffffdffffff
    ffffffffffffffffffffffffffffffffffffff6ffcbcf6fffffffffffffffffcfffffffffffffffffffffcfffffffffffffffffffffffffffffdccddcedccccccbccdcceeccccccdcccffffffffffff
    fffffffffffffffffffffffffffffffffffffff9ffbbcf9ffffffffffffffffcffffffffffffffffffffcfffffffffffffffffffffffffffffdcbcddcedcccccccccdccdcdddbbccccfffffffffffff
    fffffffffffffffffffffffffffffffffffffff9ffbbff6ffffffffffffffffcfffffcffffffffffff9fcfffffffffffffffffffffffffffffdcbcccdbceddcccccccccccccbdcccfffffffffffffff
    ffffffffffffffffffffffffffffffffffffffff6ffbbcc9fffffffffffffffccfffffffffffffffffffcfffffffffffffffffffffffffffffdcccccdce9ecdcccdbcdddddddfcfffffffffffffffff
    fffffffffccfffffffffffffffffffffffffffff6ffbbfc9ffffffffffffffffcfffffffffffffffff9ffffffffffffffffffffcffffffffffdccecccbde999bddccdfffccdcccfffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffff9ffdccf9fffffffffffffffcfffffcfffffffffff9fcfffffffffffffffffffffffffffffddcccccccee9c9999dffffddfcccfffffffffffffffff
    ffffffffffcffffffffffffffffffffffffffffff9fccbcc9fffffffffffffffcfffffcfffffffffff9fccffffffffffffffffcffffffffffffdcceccccdddceebdcffffdfcccffffffffffffffffff
    fffffffffffcffffffffffffffffffffffffffffff9ffbcc9ffffffff99fffffcfffffffccffccffccfffffccfccfffffffffffffffffffffffdccecccccccddddcfffcdfccffffffffffffffffffff
    ffffffffffffeffffffffffffffffffffffffffffff8fbdcf6fffffff99ffffffcffffcffffffffff9ffcfffffffffffffffcfffffffffffffffdccceccccccbfcccffdffcfffffffffffffffffffff
    ffffffffffffffffcffffffffffffffffffffffffff9fcbcc6fffffffffffffffcffffcfffffffffffffcfffffffffffffffcffcfffffffffffffdccceccceccccccfdfffcfffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff9fcbcc9ffffffffffffffcfffffffffffffff9ffffffffffffffffffcffffffffffffffffbdcccceeccccffddffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff9fcbcc9ffffffffffffffffffffffffffffffffffffffffbffffffffffffffcffffffffff9cbdddfccccdddeffffffffffffffeffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff9fbdcc9fffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffff6c9ffffdddddfffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffcffffffffff9ffbbc6fffffff9ffffffffffffffffffffff9fcffffffffffffffcffcffffffffffff6cc9ffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffcfffcfffffffffffffffffffffff9ccbcc9ffffffffffffffffffffffffffffbffffffffffffffffcffffffffffffffff6c9fffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffcfffcffffffffffcfffffffffff9ccbbc9ffffffffffffffffffffffffffffbfffffffffffffffcfffcffffffffffff9c6fffffffffffffffcfffffffffffffcffffffffffff
    ffffffffffffffffffffffff8ffffffffffffffffffcfff9ccdcc9fffffffffffffffffffffffffffffffffffffffffffcfffffffffffffff6cc9ffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffcffffffffffffffffccffff9cbcc9ffffffffffffffffccccccccccbcbcccccfffffffffffffffffffffffff6c9fffffffffffffffcffffffffffffffbffffffffffff
    ffffffffffffffffffffffffffcfffffffffffffffffffff9cbdc9ffffffffffffccccffffffffffffffffffccccffffffffffcfffffffff9fc9fffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffcffffffffffffffffff9ffffff9ccbc69ffffffccccffffffffffffffbfffffffffffccccffffffcffffffff9cc9ffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffcfffcffffffffffffffffffff9ccdc69ffffccffffffffffffffffffbf9fffffffffffffccfffffffffffff9c9fffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffcfffcfffffffffffffffffff9ccdcc68fffffffffffffffffffffffbf9ffffffffffffffffffcffffffff9cf9fffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffcfffcfffffffbfffffffffff9ccbcf9fffffffffffffffffffffffbfffffffffffffffffffffccfffff66f9ffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffcfffffffffffffffffffffff6cbdc9fffffffffffffffffffffffbf9fffffffffffffffffffffccfff9c66fffffffffcfffcffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffcfff8ffffffffffffffffff9ccdcc9fffffffffffffffffffffffbffffffffffffffffffffffffff9cc9fffffffffcfffcfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffcfff8fffffffffffffffccf9ccdcc9ffffffffffffffffffffffb9ffffffffffffffcfffffffffccc96ffffffffcfffcffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffff6fffcfffffffffffffcfff9ccdcc9fffffffffffffffffffffbb9ffffffffffffffc9ffffffff9c9fffffffffcfffcfffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffcffffffffffffffcfffff9fccff99ffffffffffffffffffffbb9ffffffffffffffffffffffffcc9fcffffffcfffcfffffffffffffffffffffffffffffffcffff
    ffffffffffffffffffffffffffffffffcfff8ffffffffcfffffff6ffdfff9fffffffffffffffffffbb9fffffffffffffffffffffff9c9ffffcfffcfffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffcfffcffffffcffffffff6ffdcff9fffffffffffffffffffbb9ffffffffffffffffffffff9cc9fffffffffffcffffffffcffffffffffffffffffffcfcffffff
    99fffffffffffffffffffffbbffffcffffcffffffffcfffffffff6ffcbfffffffffffffffffffffffb9fffffffffffffffffffff9cc9fffffffcfffffffffffff9ffffffffffffffffffffccfffffff
    cc99fffffffffffffffffffffffffffffffcfffffccfffffffffff9fcbdcfffffffffffffffffffb9b9fffffffffffffffffffff9c68ffffffffffffffffffff69fffffffffffffffffffffffffffff
    cccc99ffffffffffffffffffffffffffffffcfffffffffffffffff9fffcdffffffffffffffffffffbb9ffffffffffffffffffff9cc9fffffffffffffffffffffffffffffffffffffffffcffffffffff
    cccccc99ffffffffffffffffffcffffffffffcffffffffffffffffffffcdffffffffffffffffffffbf9ffffffffffffffffffff9c66ffffffffffffcfffffffffffffffffffffffffffffffffffffff
    bccceccf99ffffffffffffffffffffffffffffcfffffffffffffffffffccdfffffffffffffffffffb99fffffffffffffffffff9cc9ffffffffffffffcfffffffffffffffffffcffffffffffffffffff
    bcccecccec99fffffffbffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffdebe9ffffffffffffffffff9cc9ffffffffffffffffffffffffffffffffffffffffffffffffffffff
    cccccccbcccc9fffffffffffffffffffffffcffffffffffffffffffffffccdffffffffffffffffdcccdffffffffffffffffff9cc9fffffffffffffffffcfffffffffffffffcfffcffffffffffffffff
    ccdcccdccbcc9ffffffffffffffffffffffcfffffffffffffffffffffffffdffffffffffffffffdcdddfffffffffffffffff9c66fffffffffffffffffffcfffffffffffffcfffcfffffffffffffffff
    ccccccccbbccc999fffffffffffffffffffcfffffffffffffffffffffffffdbffddddfffffffffdbbbdfffffffffffffffff9c9ffffffffffffffffffffffffffcfffffcfffcfffffffffffffffff66
    99ccceeccccbccc699ffffffffffffffffcffffffffffffffffffffffffffffcbffdddfffffffffbbbdffffffffffffffff9c6ffffffffffffffffffffffcfffcfffffcfffcffffffffffffffff66ff
    ff999fcceccedccccc99fffffffffffffcfffffffffffffffffffffffffcbfddfdddfdffffffffffffffffffffffddddbff6c9fffffffffffffffffffffffcfffffffcfffcffffffffffffffff6ffff
    fffff99fccccccdccccc99ffffffffffcffffffffffffffffffffffffffccbffbdddfdffffffffcfcccffffffffbffffddcfb9fffffffffffffffffffffffcfffffffffcffffffffff69fff666fffff
    fffffff99cfcffceddccff99ffffffffffffffffffffffffffffffffffbfffbbbbddfdffffffffccbbdffffffffbfdddfddbffffffffffffffffffffffffffffffffff6fffffffff99ff966fffffeff
    fffffffff999ffccccdccccc999ffffcfffffffffffffffffffffffffccfbbbbbbdbdfffffffffccbbdffffffffbfddddffdbfffffffffffffffffffffffffffffffffffcfffff99ffcffffffffffff
    ffffffffffff99ccccccddccccc6f66ffffffffffffffffffffffffffcfcbbbbbbffffdddfffffccbbdfffffffffcbbbdddfbbcffffffffffffffffffffffffffffffffffffff9ffefcffeffbffffff
    ffffffffffffff999fffffddcccf9f66ffffffffffffffffffffffffffbffbbbbffddddccdffffccbbdfffffdddffbbbbddbcbffffffffffffffffffffffffffcffffffffffff9ffcfefeeffffff666
    fffffffffffffffff99fffffddccccc699ffffffffffffffffffffffffbffcfffbddbcdccdffffccbbdfffffbedddffcbddbbfbffffffffffffffffffffffffffcffffffff999cffffebffffff99fff
    fffffffffffffffffff96fffffddcccccc99ffffffffffffffffffffffbcfffbbbccbccfffffffccbbdffffbbcbbbdffffbbbfbfffffffffffffffffffffffffffcfffff66ccccfeebffffff66fffff
    fffffffffffffffffffff66fffeffdccccff99fffffffffffffffffffffcffbcccccfffddddfffccbbdfffffffbbbdddffccfccfffffffffffffffffffffffffffcff996fccccbbfccffff99fffffff
    fffffffffffffffffffffff99ffffcbdfdcccbfffffffffffffffffffffcfccccccfbbbbdeddffccbbdfffdddfffbbbbdffcfccfffffffffffffffffffffffffffc99cfcbbcbbcfcccff99fffffffff
    fffffffffffffffffffffffff9ffccccfdbbcdfffffffffffffffffffffffcfccffbbbbbdeddffccbbdfffddddbffbbcbdfffcffffffffffffffffffffffffff996cccbbdfdccffcff99fffffffffff
    fffffffffffffffffffffffff6ffffcffbbbdffffffffffddfffffffffffcffffbbbbbbbbdedffcccccffddbbeddfffcccbfffffffffffffffffffffffffff998ccccbddccffff9999fffffffffffff
    ffffffffffffffffffffffffff66ffffccccfbddffffffdcdddfffffffffcfffbbbccbbbbddddfffffffbbdddeddddffcccfbfffffffffffffffffffffff99fcfbbdbbffccf999fffffffffffffffff
    fffffffffffffffffffffffffcff99ffccccfffbdfffddfffffdffffffffbfffccbbbbcbddfbdffcccbfcffddddbddbfcccfcffffffffffdddffffffff99cccbfbbfccff666ffffffffffffffffffff
    fffffffffffffffffffffffffcffff99fffffccfcddffdfdddfefdddfffffcffcccbbbbddccccdfcbcbfbbcbdddbdcbfffcffffffffffddeeedefffffffffedbfccfff99fffffffffffffffffffffff
    fffffffffffffffffffffffffcffffff6666ffffcfffbffddddffbbdfffffccffccbcbbfffcccdfcbbbfbbcffbbbbccccfff9fffffdfbcffffddffffffddfcccfff999fffffffffffffffffffffffff
    ffffffffffffddfffffffffffcfffffffffffffffccbbfdbbddfddbffddddfffcccccfffcccffddbfffdffccfffbcbccffffffffddddfffddffbffffddcccfff999fffcffffffffffffffffffffffff
    ffffccfffffffffffffffffffcffffffffffffffffffbfbbbbdfddbfdbdddbdffccccfccfccfddddddddfccfccfccbcfcfffffffffbddfbdddfbfddcffffff69ffffffcffffffffffffffffffffffff
    ffffffcccccfffffffffffffcffffffffffffffffffbfbbbbbfbdbfbdeeddeddcfffffccfcbfddddddddfbcfcccfcfcffffdddddffbddfbdddfedffcff9999fffffffffcfffffffffccffffffffffff
    fffffffffffffcccffffffffcfffffffffffffffffbfccbbcfbbbffbbddddddddeddfcfccffdfccccccccfdfcfcfcfffcddddeeddfbbddfcbbbfbfcffffffffffffffffcfffffffffcfffffffffffff
    ffffccccfffffffffcccffffcfffffffffffffffffbffccccfbcbfbbcbbbbfffffddfccffcfdfccccffccfdfffccfbcdfcfbdbdddbfbbdbfbbbbfcfffffffffffffffffcfffffffffcfffffffffffff
    fffffffffccffffffffffffffffcffffffffffffffbffcccffbcbfbbcbbbbdfbbbccefffccfdfcffcfcccfdccfffbddbcdfbdddddbfbbbbfcbbbfbfffffffffffffffffcfffffcfffffffffffffffff
    ffffffffffffccccffffffffffff9ffffffffffffffcfffcfcccffbbbbbbbffcbffffddfccfdfccccfcccfdcfdddfffbbfffbbbbbbfccbbfcccbfcfffffffffffffffffcfffffffffffffffffffffff
    fffffffffffffffffccffffffffffffffffffffffffccffffcccffbbccbbbbfffcbfbbdfccfdfcccffcccfdcfdddfcbbbfcfbbbbbbffccdcfcccffffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffcffffffffffffffffffffffccccffcfccbbcbfffccfffcbbbcfcfdfffffffffcdfbbbdddfffccfbbbbbcbfccccfcfffcffffffffffffffffffcffffffffffffffffffffff
    ffffffffffffffffffffffcfffffffffffffffffffffffffcffffcccbbbffdfbbffbbbcbfccc99ffffcfddbfcbbbddffbccffbbbcbbfffccffffcfffffffffffffffffffcffffffffffffffffffffff
    ffffff9fffffffffffffffcfffffffffffffffffffffffffcfffffcccccfbbffffbbbbcbfccccfffffcfccbfcbbbbddffffbfbccbcccfffcffccffffffffffffffffffffcffffffcfffffffffffffff
    ffffff9fffffffffffffffcffffffffffffffffffffffffffccffffccccfcfccffbbbbccfccccf66cccfccbfcbbbbddffbbbbfcbccccfffcfffffffffffffffffffffffffffffffcffffffccccfffff
    fffffffffffffffffffffcffffffffffffffffffffffffffffffcfffffffccccfbbffffffffccff6ffffccfcffffffddebbfcfccccccffccfffffffffffffffffffffffffcffffffccccccfffffffff
    fffffffffffffffffffffcfffffffffffffffffffffffffffffffccffffffcccfbbfbbbffffffccccccccffbffeeefddffbfcfcccfcccffffffffffffffffffffffffffffcfffffffffffffffffffff
    fffffffffffffffffffffcfffffffffffffffffffffffffffff6fffccccffffffbbcbbbffcfffccccccfffcbffbbbfddfffffcccccccfffffffffffffffffffffffffffffcfffffffffffffffffffff
    fffffffccffffffffffffcfffffffffffffffffffffffffffff9fffffffccccffbbcbccffcccfffffffffcbbffffcfddfcbebfffccfffffffffffffffffffffffffffffffcfffffff6fffffffffffff
    fffffffccffffffffffffcfffffffffffffffffffffffffffff9ccfffdddcccffbbcbbbbffcccfffffcfccbffbbbcfddfcccddddfffffffffffffffffffffffffffffffffcfffffffffffffffffffff
    fffffffccffffffffffffcfffffffffffffffffffffffffffff9fffbbddffddffcbcccfbffccccccccccbbcffffffcbdfcccfcdbdddffffffffffffffffffffffffffffffcffffffffffffffff9ffff
    fffffffffffffffffffffcfffffffffffffffffffffffffffffffbbbbddfdbffffbbfbbbbffcccbbbcbbbccfbbbbfbbcfffddbfbddddfffffffffffffffffffffffffffffcffffffffffffffff9ffff
    fffffffffffffffffffffcffffffffffffffffffffffffffffbbbfbbbffffffcffbbbfcbbfffccccccccfcfcbbbccbdcfcfffcbddeddfdddfffffffffffffffffffffffffcffffffcfcffffffffffff
    fffffffffffffffffffffcffffffffffffffffffffffffffffbbbfbcbcbfccccffcfbcccccffcccccccccffbccccbbffffbbcfbbdddbfbddfffffffffffffffffffffffffcfffffffffffffffffffff
    fffffffffffffffffffffcfffffffffffffffffffffffbbbfbfbbbfbbbbbccccfffcbbccccccffcccccffccccccbbbffffffffbbdddffdddfddbfffffffffffffffffffffcfffffffffffffffffffff
    fffffffffffffffffffffcfffffffffffffffffffffddffffbbbbbfbbbbbffccfbffcbcccccccffffffccccbbbcbbfffffcbcbcbbbcfbbdfdedddffffffffffffffffffffcfffffffffffffffffffff
    fffffffffffffffffffffcfffffffffffffffffffffbffccbfbbbbffcbbbbcfffbcffcbbccccccfcccfcccccccddfffddfffcbcbbbffbbdfdceeddfffffffffffffffffffcfffffffffffffffffffff
    fffffffffffffffffffffcffffffffffffffffffffbfbbccbffbbcbfbccbbffddfcffffcbbccccfffcfcccccddffffbbbddfcccccffbbbffddfefdfffffffffffffffffffcfffffffffffffffffffff
    ffffffffffffccfffffffcffffffffffffffffffffbfbbbbcbfbbbbfcbccccfbfffffccfffccccfffcfcccbbfffcfffffbffcccccfcbbbfbdddbfdfffffffffffffffffffcffffffccfffffffffffff
    ffffffcffcccfffffffffcfffffffffffffffffffffcccbbbcbfbcbbfcccccffcccfffccccfffcfcccccccfffffffffcccfccfcccfbbbffbbbdcfdfffffffffffffffffffcfffffffffccfccfffffff
    ffffcffffffffffffffffcfffffffffffffffffffffbccbbbbbffbbbffcccccfcffffffcccccfcfccccbbbfffffffffffffcccccffbbbfcbbbdffdfff699fffffffffffffcfffffffffffffcfffcfff
    ffffffffffffffccffffffcffffffffffffffffffffbffcbccccfbcbffccccccffffbcffffbfbfccccccfbffffbffbcffffffcccffbbfccccbffdfffffee99fffffffffffcfffffffffffffffffffff
    fffffffffcccffffffffffcfffffffffffffffffffffcbfcbcccfbccffcccfffffcfbffcffbfbfccccccfbfcffbffbbffffffffffccbfccbbbfccbbfdeeecf99fffffffffcfffffffffffffffffffff
    fffcccccffffffffffffffcffffffffffffffffffffbfccfbcbcffcccfcfffcfffccbfbfffffbffcccccfbfffffcfcfbbffffffffffffcfccffcfcbdfdeebfff99fffffffcffffffcffffffffffffff
    fffffffffffffffff99fffcffffffffff999ffffffdbcfcfcccccfcccffcccfffbfcfccffbfffc6ccdddffbfdffccfcffffccccffffffffccffccccfbbdddfbeff99ffffcffffffffffffffffffffff
    fffffffffffffffff99fffcfffffffff9ffbbffcbcffcfcfcbccccfcfcfffffffcccfffffbfbffffffffffcfdfffffccccffffcccfffffffcfcfffffccccfbbbbfcf99ffcffffffffffffffffffffff
    fffffffffffffffffffffffcffffff99fcbbbcbffccccfcfccccccfcfcffffffcccfffcfbbfbffffffffffebbbfcfcfcccffccfff66fcbffffcfffffccccfbbbdfcccc999ffffffffffffffffffffff
    fffffffffffffffffffffffcffff99fcfcbbcbfcccffbcffcfcffffcccfffcffccccffcfcffbf6666666ffdcfffcffccccbfcffc9fffffbcccfffffffffffcccfcddccccc99ffffffffffffffffffff
    fffffffffffffffffffffffcffffffbbbfbccbbffffffcbfcccfffffffffccfccccccccfccccfffffffffffcccffcccbbbbfffcf6fffffffffffffff66fffcccfcccddccccc999fffffffffffffffff
    ffffffffffcfffffffffffffcfffcbbbbfbccccfffffffccccfcfcffffccfffccbcccccffcccffcffcfcfffccfcfbbbcbbbbfcf66fffffffffffffffff96fffffffcffddbccccc669ff99ffffffffff
    ffffffccffffffffffffffff669fcbbbbffccccffffffffccccfffffccffffccfccccccccfffffcffcfcfffffcccbbccbbbcfc66fffffffffffffffffff999ff666fffffcddcccccc99cc99ffffffff
    ffccccfcffffffffffffff99fffdcfccccfcccfffffffffcffffffccffffffffbbcccccccfcfffccccccfffcccccbbbbfffccf66ffffffffffffffffffffff99fff666fffffdddcccccbdff999fffff
    ffffffffffffffffffff69ffccbbcffcccfccfffffffffffccffccffff6ffffffffbcccccccffccccccccffcccccbbcffbbccffcffffffffffffffffffffffffffffff666fccccddcccccbdccc99fff
    ffffffff6fffffffff666cccbbccfffffffffffffffffffffcccffffff66fccccccffcccfccffccccccccffcfccccffcbbbbbbffcffffffffffffffffffffffffffffffff99ccccccbbccccceccc999
    fffffffffffffffc99cccbbbffff6fffccfffffffffffffffffffffffff6fccccccccfffcccffcccccfcfcffcffffbbbbcbbcbffbffffffffffffffffffffffffffffffffff99fccccbcdedcccccccc
    ffffffffffff999fcccddccfff66f999cffffffffffffffffffffffffffffccccccccccfffcffcccccfcfcffcffcccbbbbcbbbfffbfffffffffffffffffffffffffffcfffffff99ccceeccccdcccccc
    fffffffffff6fffcbbdccfff66ffffffffffffffffffffffffffffffffffffffffbccccccfffccbb6cbcfcfffcccbbbbbcbbbfcffbfffffffffffffffffffffffffffcfffffffff99fccccccecccdcb
    fffffffff666cbbbbcffff66fffcffffffffffffffffffffffffffffffffbfcccfccbcccfcffcfffffffccfffcfcbbbbbbbffccffbbfffffffffffffffffffffffffcffffffffffff999ccccccccbcb
    fffff6666cccbddfccff66fffffcffffffffffffffffffffffffffffffffccccccfffcccfcffccccccccccfcfcfccbbbbffccbbfffbbffffffffffffffffffffffffffffffffffffffff99ccccdcccc
    ff666ffffcdddfffccf6ffffffffcffffffffffffffffffffffffffffffbfccccccccffcfcfffffffffffffcffccccffffcccbdfcfbbfffffffffffffffffffffffcffffffffffffffffff99ccccccc
    66ffffcccfcccfccff96ffffffffcffffffffffffffffffffffffffffffbfcccccccccfffcffffccccccffffffcfffcccccbbbcfcfcbffffffffffffffffffffffffffffffffffffffffffff999cccc
    fffffffffffffff666fffffffffffcffffffffffffffffffffffffffffbffccccccccccfffffffccccccffffcffccccccbbfffffccfcdfffffffffffffffffffffcffffffffffffffffccffffff99fc
    ffffefffffff666ffffffffffffffcffffffffffffffffffffffffffffbfccfffbcccccfffffffccccccffffcffcccbbbcffbfcccccfdffffffffffffffffffffcfffffffffffffffffffcfffffff99
    ffbffffffff6fffffffffffffffffffffffffffffffffffffffffffffffcffccfffcccfffffffffffffffffffcffffffffcfdffccccfdffffffffffffffffffffcfffffffffffffffffffffffffffff
    fffffff6666fffffffffffffffffffcffffffffffffffffffffffffffffcffffccffcfccffffffffffffffffffcccfccccccfdfccccdffffffffffffffffffffcffffffffffffffffffffffffffffff
    ffffff6ffffffffffffffffffffffffcffffffffffffffffffffffffffffcfccfccfffccffffffffffffffffffcfcfccccfcfbffccdbffffffffffffffffffffffffffffffffffffffffcffffffffff
    ffff99ffffffffffffffffffffffffffcfffffffffffffffffffffffffffffccfcfcfcccffffffffffffffffffccccfccccfbfdfbbfffffffffffffffffffffcfffffffffffffffffffffffffffffff
    ff99fffffffffccffffffffffffffffffcffffffffffffffffffffffffffffbfcfccfcffffffffffffffffffffcbfcffcccfbfbdffffffffffffff9fffffffcffffffffffffffffffffcfffffffffff
    66ffffffffffcffffffffffffffffffffcfffffffffffffffffffffffffffbfccfffffffffffffffffffffffffbbfcfccccffcfdffffffffffffffffffffffffffffffffffffffffffcffffffffffff
    ffffffffffffffffcfffffffffffffffffcffffffffffffffffffffffffffbfcfffffffffffffffffffffffffffbfcfcccccfbfdfffffffffffffffffcfffffffffffffffffffffffcfffffffffffff
    fffffffffffffffcfffffffffffffffffffcffffffffffffffffffffffffcfcffffffffffffffffffffffffffffbbbbbbbbccfffdffffffffffffffffffcfffffffffffffffcfffffcfffffffffffff
    fffffffffffffffcfffbffffffffffffffffcfffffffffffffffffffffffcfcffffffffffffffffffffffffffffffffffffffffffdbf69fffffffffffffffcffffffffffcfcfffffcffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfcfffffffffffffffffffffffffffffffffffffffffcbbbbf9ffffffffffffffffcfffffffccffffffffcffffffffffffff
    fffffffffffffffffffffffffffffffffffffcffffffffffffffffffffcfccffffffffffffffffffffffffffffffffffffffffcccbbdff9fffffffffffff8fffffffff66fffffffffffffffffffffff
    ffffffffffffffffffcffffffffffffffffffffffffffffffffffffffccccffffffffffffffffffffffffffffffffffffffff9fccbffff9ffffffffffffffcfffffffffffffffffffffffffffffffff
    ffffffffffffffffffffbffffffffffffffffffffffffffffffffff9fcbbcffffffffffffffffffffffffffffffffffffffff9fccfdffc9ffffffffcffffffccffcffffffffffffcfffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffff9fccccffffffffffffffffffffffffffffffffffffffff9ffcccbccc9ffffffcfffffffffcffcffffffffffcffffffffffffffff
    fffffffffffffffffffffbffffffffffffffffffffffffffffffff9ffccccfffffffffffffffffffffffffffffffffffffffff9fcfcbccc9fffffcfffffffffff8fffffffffffcfffffffffffffffff
    ffffffffffffffffffffffffffffffffffffcffffffffffffffff9ffbcffcffffffffffffffffffffffffffffffffffffffffff9ffffdccc9fffcfffffffffffffcffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcfffffffcfffffff9ffbcff6fffffffffffffffffffffffffffffffffffffffffff9fffcdcc99ffffffffffffffffffcffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffccffff9ffbffc6fffffffffffffffffffffffffffffffffffffffffffff9fffdccfc9ffffffffffffffffffcffffcffffffffffffffffffff
    ffffffffffffffffffffffcffffffffffcffffffffffffffcfff9ffbff6ffffffffffffffffffffffffffffffffffffffffffffff9ffffbcff9ffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffcffffffffffcffcfffffcfffffffff9ffdcff6fffffffffffffffffffffffffffffffffffffffffffffff9ffcdfff9ffffffffffffffffffffff8fffffffffffffffffffff
    fffffffffffffffcffffcffffffffffcffcffffffffffffffff9ffdff6ffffffffffffffffffffffffffffffffffffffffffffffff96fffdfff9ffffffffffffffffffffffff8fcffffffffffffffff
    ffffffffffffff6cffffffffffffffcfffcffffffffffffffff9cbbff6fffffffffffffffffffffffffffffffffffffffffffffffff6fffccff9ffffffffffbfffffffffcfcffffffffffffffffffff
    fffffffffffffffffffffffffffffcfffcffffffffffffffff9fcbff9ffffffffffffffffffffffffffffffffffffffffffffffccfff9ffcdfff9ffffffffffffffffffffffcfffffffffffffffffff
    ffffffffffffffffcfffffffffffcfffcfffffffffffffffff9fcbff9fcffffffffffffffffffffffffffffffffffffffffffccfffff9ffffdff9fffffffcfffffffffbffffffcffffcffffffffffff
    fffffffffffffffcfffffffffffcfffcfffffffbfffffffff9ccdff9fffcccfffffffffffffffffffffffffffffffffffccccffffffff9fffdff9fffffff9fffffffffffffffffcfcffffffffffffff
    ffffffffffffffffffffffffffcfffcffffffffffffffffff9fbbff9ffffffccccffffffffffffcffffffffffffffccccffffffffffff9ffffcff6ffffffffffffffffbbfffffffffffccffffffffff
    ffffffffffffcffffffffffffcfffcffffffffffffffffff9fcbff9fffffffffffcccccfffffcccffffffffffccccfffffffffffffffff9fffdff6ffffffffffffffffccfffffffffffffffffffffff
    ffffffffffffffffffffffffcfffcfffffffffffffffffff6cbcff9ffffffffffffffffcccccffffcccccccccfffffffffffffffffffff98fffcfff9ffffffffffffffffffffffffffffcffffffffff
    fffffffffffffffffffffffffffcfffffffffbdffffffff9fcdcf9fffffffffffffffffffffffffffffffffffffffffffffffffffffffff9fffdfff9fffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffcfffffffffffffffffff9ccbcff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffdfff9ffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffcffffffffffffffffffff9ccbcf9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9fffdfff9ffffffffffffffffffffffffffffffffffffff
    ffffffffcfffffffffffffffccfffffffcfffffffffff9fcddcf9ffffcffffffffffffffffffffcfffffffffffffffffffcfffffff6bffff9ffffdfff9fffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffcffffffffffffffffffff9ccdff9fffffffffffffccfffffffffffbccffffffffffffffffffcffffff9ffffff9fffdfff9fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffcffffffffffffcfffffff9fcbbff9ffffffffffffffffffffffffccccffffffffffffffffffffffffffffffffff9fffbfff9fffffffffffffffffffffffffffffffcefff
    ffffffffffffffffffffffcfffffffffffffffffffff9fbbff9ffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffff9fffbfffc9ffffffffffffffffffffffffffffffffffe
    fffffffffffffffffffffcffffffffffffffffffff99ffbbcc9fffffffffffffffffffffffffffffffffffffffffffffccffcfffffffffffff9fffccfff9fffffffffffffffffffffffffffffffffcf
    ffffffffffffffffffffcffffffffffffffffffff9fcfcbff9fffff9ffffffffffffcfccffffffffffffffffffffcccffffffffffffffffffff9ffffbfff9ffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffff9ccfbbc69ffffffffffffffffffffffffccfcccfccffccffccffffffffffcfffffffffffff9ffffcfff99fffffffffffffffffffffffffffffffff
    fffffffffffffffffffcffffffffffffcfffffff9fccdcff9fffff9ffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffff9fccffffff9ffffffffffffffffffffffffffffffff
    ffffffffffffffffffcfffffffffffffcfffffff9fccdcf9ffffff9fffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffff9fccffffff9ffffffffffffffffffffffffffffffff
    fffffffffffffffffcfffffffffffffbfffffff9fbffccf9fffffffffffffffffffffffffffcffffffffffcffffffffffffffffffffffffffffff9fcffffdff9fffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffeffffffff9cccbff9fffffffffffffffffffffffffffffffffffffffcffffffffffffffcffffffffffffffff6fffbcfff6fffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffff9feccbff9fffffffffffffffffffcfffffffffffffffffffcfffffffffffffffff8fffffffffffff9ffffbfff66ffffffffffffffffffffffffffffff
    ffffffffffffffcfffffffffffffffffffffff9fecbcff9ffffffffffffffffffffffffffffcffffffffffcfffffffffffffffffcfffffffffffff6ffffceccf6ffffffffffffffffffffffffffffff
    ffffffffffffcffffffffffffffffffffffffffcfbbef9fffffffffffffffffffffffffffffcffffffffffcfffcffffffffffffffffffffffffffff9ffccbffff9fffffffffffffffffffffffffffff
    ffffffffffffcfffffffffffffffffffffffffffcefff9ffffffffffffffffffffffffffffffffffffffffcfffffffffffffffccfffffffffffffff9ffcfffccf9fffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffff9fdccfc9ffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffff9fffebffcf6ffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffcdffff9fffffffffffffffffffeffffffffffffffffffffcffffffffffffffffffffffffffffffffff6ffffbfff6ffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffff9df9f9ffffffffffffffffffffffffffffffcfffffffffffcffffffffffffffffffffffffffffffffff6ffffbffff6fffffffffffffffffffffffffff
    fffffffffffffffffbffffffffffffffffffff9ff9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff96fffbffff6ffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffdcf9ffffffffffffffffffffffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffcffff6ffffffffffffffffffffffffff
    ffffffffffffccfffffffffffffff6fdddccddcbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6cfcfbcccf6fffffffffffffffffffffffff
    fffffffcffffeeefffffffffffffdddcffccdb9dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fcffcccf6fffffffffffffffffffffffff
    ffffffcfffffffffffffffffffddcccceeecccfdfffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fcffbcccf6ffffffffffffffffffffffff
    fffffeffffccdddbbdfccfffddcccccccccccccddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8cfffffcf6ffffffffffffffffffffffff
    ffffeffffffdccccccdccffdfcccccccceccccccdbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6cfffbefff9fffffffffffffffffffffff
    fffffffffccccccccccbcbbccccccccbcceeeccccbfffffffffffffffffffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffefffcfff6fffffffffffffffffffffff
    fffffffffcdccfffffcbcfdcccccbddbcfeecccccbdffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffebfcf6ffffffffffffffffffffff
    ffffffffcccfffffffccbdccccfdde9ddbcceccccddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fcffffcf66fffffffffffffffffffff
    ffffcccccdffffffffccdccfddbdeeeccddccccccfbdfffffffffffffffffffffffffffffffffffffffffffffdffffffffffffffffffffffffffffffffffffff6fcffbfff6fffffffffffffffffffff
    fffcffccbbfffffffccfdbdddcbceee9edebcccecfcdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fccffffff9ffffffffffffffffffff
    ffffcfddfffffffffccddcccccecddeddc9ddfcecfdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffcdfff9ffffffffffffffffffff
    cccbbbffffffffffccdbcdddccccceddc999dfceccdffffffffffffffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9ffcffceff6fffffffffffffffffff
    fffffffffffffffccdccdccccccccccded9cbbbeccdffffffffffffffffffefffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9ffccddffff6ffffffffffffffffff
    fffffffffcfffddddddbccccccdccccccddbedffffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffccf6ffffffffffffffffff
    fffffffccfdddccccccdcccccccccccccccdddffffdfffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6fffbdffff9fffffffffffffffff
    ffffffcddccccddcc99cdccccccdddccbccdcdffffdffffffffffffffffffffffffffffffffffffffffffffffffefffffffffffffffffffffffffffffffffffffff6ffffffffff6ffffffffffffffff
    fffffccdccbccccdddc95cccccdeccbccccdcdffcdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffdffff6ffffffffffffffff
    ffffccdeccccccccccc99dcccdccecdbcccdcdffdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6ffffdffccdffffffffffffffff
    fffcdddccccccccccccddccbdccedcebccdbcdcfdfffffffffffffffffffffffffffffffffffffffffffffffffdfffcffffffffffffffffffffffffffffffffffffff6ffffbdeccdfffffffffffffff
    ffcdcccccdccdcccbccbcccdcccbcccdccdcdecdcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfbdeecbfffffffffffffff
    fcdcccdccdccbccccecdcccdccdeccbcccdcecdccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdccccdeccfdffffffffffffff
    cdcccdecccdecccdccebccbdccbcccdcccdebfdcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdccccceeecfdfffffffffffff
    dccedcccccdecceeebeeeeecedeccdccccdececffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffdccccdecccdffffffffffffc
    cccdcccccceeeeeeeeeecdccdcebecccdccccdfcfffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffdfccffeccccdfffffffffffc
    ccdeeeedeeeeedeeeeeccdcddcccdcccdccbcdfcfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffdfcccceeecddffffffffffc
    ccdeededeeeeeedeeeedcccdceddecccbdddccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffdfccccceeccedffffffffff
    ccdeedeeeeeeeeeeeeebccedddceeeee9ccedcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdcccccdeeccdffffffffff
    fdeeeeeeeeeeeededeeeeeeeecccccbeccccdccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdcccccceecccdffffffffc
    deeeeeeeedeeeeeeeeeeeeebbccccccd9ccccdccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdfccccccbeccdffffffffc
    eeeedeeeeedeeeeeeeeedecccdeeeccc955bcdccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccedccceccdfffffffff
    eeebbeeeeeeeedeedeeeecdeedecedccc95bcdccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdccceceeeccdfffffffc
    eeeeeeeeeeeeeeeeeeeeedeceeeeecccce5edcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdcccdeeeeccddffffffc
    eeeeeeeeeeeeeeedeeeeeecceedbcccccdccdcccffffffffffffffffdffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcdccccccecccdffffffc
    feeeeedeeeeeeeeeeeedeeeeeebbeccccccdeccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdccccdceecccdfffffc
    feeeddedeedeeeeeeeeeeeeeeeeccdcccccdcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdccceeeeeccdffffcf
    eeedeeeeeeeeeeeeeeeeeeeeeeeeccddccdbcdcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfdcceeeeeecccdfffcc
    cfeeeeeeeeeeeedeeeedeeeeeeeeecccddcccdcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdccceeecebecdccffc
    cfdeeeebdeeeeeeeeeeeeeeeeedeeeeedecccdcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfdcceeeeeebcdfccfc
    cffeeeeddeeeeeeeeeeedeedeeeeeeeeccccdccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccdcccceeeecccdcccc
    cffeeedeeeeeeeeeeebeeeeeeeeeeeedccccdccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccf9cceeeeebcccdccc
    cccfedeeeeeeeeeeeeedeeeedeeeeedecccdcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfd9ceeceeecccdccc
    cccfceeeeeddeebeeeeedeeeeeeeecdeccddccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcff9ceeeecebcccdcc
    ccccceeeeeedeebdeeeeeeeeeeeeedeeccdcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccf9ceeeeeeceecdfc
    ccccccfdeeeeeddddeeeeeedeeeedeeeedcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffc99eeeeeeeeeeeddc
    ccccccccffeeeeeeeeeeeeeeeededeeecdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccc9ceeeeeeceeecede
    ccccfceccceeeeeeeeeeeeeeeeddeefedfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbcfcccfceeeeeeeeeeeeedf
    ccccfccccceeeeeeeccccdeddddffeffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccffeeeeeeeeeeeeeeef
    cccfccccccceeeeeccecfccccfffffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccdfffeeffeeeedeeddeeee
    `)
game.splash("To Drive Away Evil Satellites! ")
info.setLife(3)
// background can scroll
scroller.scrollBackgroundWithSpeed(0, 20)
myShip = sprites.create(img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .......66.......
    ......6999......
    .....969699.....
    .....666666.....
    `, SpriteKind.Player)
myShip.setStayInScreen(true)
myShip.y = 105
animation.runImageAnimation(
myShip,
[img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .4.....66.....4.
    ..5...6999.....5
    .5...969699..5..
    ..5..666666...5.
    .......4.4......
    ......4.4.4.....
    ................
    ................
    `,img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .4.....66.....4.
    ..5...6999...5..
    .....969699.....
    .4...666666....4
    .......454......
    ......45454.....
    ................
    ................
    `,img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .4.....66.....4.
    ..5...6999...5..
    .5...969699...5.
    .....666666.....
    .......454......
    ......45454.....
    ........5.......
    .......5.5......
    `,img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .5.....66.....5.
    ..4...6999...4..
    .....969699.....
    .....666666.....
    .......454......
    ......55455.....
    ........54......
    .......4........
    `,img`
    .......99.......
    .......99.......
    ......6666......
    ......9969......
    .....966666.....
    .....666666.....
    .....699666.....
    44...699666...44
    96...669666...66
    9666.669666..696
    6666.699666.6666
    96d66696666.6d96
    96d.669966666d96
    96d..669666..d96
    66d..699666..d66
    9dd..669666..dd6
    .5.....66.....5.
    ..4...6999...4..
    .....969699.....
    .....666666.....
    .......4.4......
    ......4.5.4.....
    .......5.5......
    ........4.......
    `],
500,
true
)
timer.after(1500, function () {
    game.showLongText("Press A and to deploy Roo", DialogLayout.Bottom)
})
timer.after(6000, function () {
    game.showLongText("Press Up/Down Left/Right to Move the Roo!", DialogLayout.Bottom)
})
timer.after(14000, function () {
    game.showLongText("Press B + Arrow Keys to Move the Ship!", DialogLayout.Bottom)
})
timer.after(24000, function () {
    game.showLongText("Don't let meteoroid hit your ship!", DialogLayout.Bottom)
})
// move the ship on a combo press
game.onUpdate(function () {
    // Dash Right combo: Holding B + Right Arrow
    // Regular Right movement without B
    if (controller.B.isPressed() && controller.right.isPressed()) {
        // Fast dash speed
        myShip.x += 2
    } else if (controller.B.isPressed() && controller.left.isPressed()) {
        // Normal speed
        myShip.x += -2
    }
})
game.onUpdateInterval(2000, function () {
    // do not have too much ememy at the start
    timer.after(20000, function () {
        mySat = sprites.createProjectileFromSide(img`
            .........bb.........
            .........bb.........
            bbbbbb...cc...bbbbbb
            ccbbbcb.b11b.bcbbbbc
            ccccccccd11dcccccccc
            cbbbbbc.d11d.cbbbbbc
            cccccc..b71b..cccccc
            ........d11d........
            .........77.........
            ........bccb........
            .......bccccb.......
            .......cccccc.......
            ....................
            ....................
            ....................
            ....................
            `, 0, 25)
        mySat.x = randint(5, 155)
        mySat.setKind(SpriteKind.Satellite)
    })
})
game.onUpdateInterval(1500, function () {
    timer.after(24000, function () {
        myRock = sprites.createProjectileFromSide(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . c c c . . . . . . 
            . . . . . . a b a a . . . . . . 
            . . . . . c b a f c a c . . . . 
            . . . . c b b b f f a c c . . . 
            . . . . b b f a b b a a c . . . 
            . . . . c b f f b a f c a . . . 
            . . . . . c a a c b b a . . . . 
            . . . . . . c c c c . . . . . . 
            . . . . . . . c . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, 0, 67)
        myRock.x = randint(5, 155)
        myRock.setKind(SpriteKind.Enemy)
    })
})
